spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=rest
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.changelog/changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
