spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=rest
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
