CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    COUNTRY_ID BIGINT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID)
);
